version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: choko_db
    restart: always
    environment:
      POSTGRES_USER: choko_user
      POSTGRES_PASSWORD: choko_password
      POSTGRES_DB: choko_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
